### ISSUE TITLE
[HZN-71] SpRes-mavis_deriv function problems

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#71] opened 2021-08-06 09:35 UTC
Transferred by @LaurenceJackson on Aug 9, 2020, 18:23

:::Issue recreated from Jira issue [HZN-71](https://gsttmri.atlassian.net/browse/HZN-71):::

Imported from https://bitbucket.org/gsttmri/hazen/issues/72/spres-mavis_deriv-function-problems  1. The calculated gradient \(L22\) is double the actual gradient. This can be shown with `mavis_deriv(_,range(10)) `which returns an array of 2.0s, rather than 1.0s. As the MTF is normalised this bug does not effect the final return value.2. The docstring does not accurately reflect the function’s behaviour.3. The function takes five input arguments but only uses one of them \(`a`\). Consider removing unused variables.4. Consider adding a reference to any published literature etc. which recommends this method of differentiation over e.g. standard Newton difference quotient [https://en.wikipedia.org/wiki/Numerical\_differentiation](https://en.wikipedia.org/wiki/Numerical_differentiation)‌

**Comment by Lucrezia-Cester** [comment] 2021-11-22 10:21
Hello @hshuaib90 , @laurencejackson, 

As I mentioned to Haris, I cannot find the literature for the MAIVIS function. 

What I found in the literature in order to calculate the LSF is this function http://sciencewise.info/resource/line_spread_function/Line_spread_function_by_Wikipedia
(basically {LSF} ={d}{dx}  {ESF} (x)). 

I then used the above function instead of MAIVIS. I attach the resulting images. 

Let me know if this alternative resolution to the issue is ok or what you would rather see implemented. 



![results_with_derivative_function](https://user-images.githubusercontent.com/83493021/142844467-b2ff6d62-4bc3-444b-a872-5cea4c26241d.png)

![results_with_MAIVIS](https://user-images.githubusercontent.com/83493021/142844479-942ef2f6-dfab-488a-8018-f4b4ce604918.png)

**Comment by tomaroberts** [comment] 2021-12-22 12:14
Addressed by PR #191

**Closed as completed by tomaroberts** 2021-12-22 12:14 UTC
Labels: major
