### ISSUE TITLE
[HZN-106] Don't use magnitude equation in T1 relaxometry fit

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#105] opened 2021-08-06 09:38 UTC
Transferred by @LaurenceJackson on Apr 23, 2021, 17:09

:::Issue recreated from Jira issue [HZN-106](https://gsttmri.atlassian.net/browse/HZN-106):::

The T1 relaxometry inversion recovery sequence results in a signal changing from -S0 to +S0 as TI increases. The acquired signal is usually rectified and the current method attempts to fit this magnitude data to abs(decay equation). This can result in the solver finding a local minima where a low signal point is fitted on the wrong side of the signal inversion.

This could be avoided with the following algorithm:

for n = 0..number_samples:

     making the first _n_ signal points negative

     fit relaxometry curve

     store mean-square-error

then using the _n_ with the lowest mse.

**Comment by tomaroberts** [comment] 2023-06-30 15:21
Closing as it is duplicate of https://github.com/GSTT-CSC/hazen/issues/101

**Closed as completed by tomaroberts** 2023-06-30 15:21 UTC
