### ISSUE TITLE
Hazen throws error when requesting Hazen version

### ISSUE THREAD

**Issue by francescopadormo** [GSTT-CSC/hazen#205] opened 2022-01-18 11:21 UTC
**Describe the bug**
Hazen throws error when requesting Hazen version

**To Reproduce**
On macOS BigSur
1. Clone git directory: git clone https://github.com/GSTT-CSC/hazen.git 
2. Copy hazen-app as suggested on website: cp ./hazen-app /usr/local/bin
3. Enter hazen-app -h (this works, as shows Hazen splash screen)
4. Enter hazen-app -v (this throws an error, as screenshot below)

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/12139443/149927953-a9e17e20-0d19-4398-b4ec-098b4489b77f.png">

**Expected behavior**
Not sure - presumably a display of the version number

**Comment by tomaroberts** [comment] 2022-01-18 11:32
Dear Franceso, thanks for raising the issue – I think this is a duplicate of issue #180, so I will close this and we will progress on there. Thanks!

**Closed as completed by tomaroberts** 2022-01-18 11:32 UTC
Labels: bug

**Comment by laurencejackson** [comment] 2022-01-18 12:15
@francescopadormo, it looks like you might have a slightly older version of hazen-app in your path. This doesn't
't get updated very often but has been recently. Could you try re-copying the hazen-app script `cp ./hazen-app /usr/local/bin` and trying again? This should fix the `-h` flag. 

There is an unresolved bug #180 which prevents the version being returned by the `-v` flag, but if you use the full  `--version` flag you should get the correct version printed.

Hope that helps!
